### PR TITLE
Develop

### LINKED ISSUE #166: import ofxCv.h give error: ‘cv::Size2d’ has not been declared
I'm using the last version of master branch of openFramework and the last version of develop branch of ofxCv.
I'm using GNU Make 3.81 under linux Mint 17.1 64bit.

Compiling the project "example-face" give me these errors:
<pre>
In file included from /home/giulio/git/openFrameworks/addons/ofxCv/src/ofxCv.h:22:0,
                 from /home/giulio/git/openFrameworks/addons/ofxCv/example-face/src/ofApp.h:4,
                 from /home/giulio/git/openFrameworks/addons/ofxCv/example-face/src/ofApp.cpp:1:
/home/giulio/git/openFrameworks/addons/ofxCv/libs/ofxCv/include/ofxCv/Calibration.h:30:67: error: ‘cv::Size2d’ has not been declared
         void setup(float focalLengthMm, cv::Size imageSizePx, cv::Size2d sensorSizeMm, cv::Point2d principalPointPct = cv::Point2d(.5,.5));
                                                                   ^
In file included from /home/giulio/git/openFrameworks/addons/ofxCv/src/ofxCv.h:22:0,
                 from /home/giulio/git/openFrameworks/addons/ofxCv/example-face/src/ofApp.h:4,
                 from /home/giulio/git/openFrameworks/addons/ofxCv/example-face/src/ofApp.cpp:1:
/home/giulio/git/openFrameworks/addons/ofxCv/libs/ofxCv/include/ofxCv/Calibration.h:31:58: error: ‘cv::Size2d’ has not been declared
   void setup(Mat cameraMatrix, cv::Size imageSizePx, cv::Size2d sensorSizeMm = cv::Size2d(0, 0));
                                                          ^
/home/giulio/git/openFrameworks/addons/ofxCv/libs/ofxCv/include/ofxCv/Calibration.h:35:3: error: ‘Size2d’ in namespace ‘cv’ does not name a type
   cv::Size2d getSensorSize() const;
   ^
/home/giulio/git/openFrameworks/addons/ofxCv/libs/ofxCv/include/ofxCv/Calibration.h:45:9: error: ‘Size2d’ in namespace ‘cv’ does not name a type
         cv::Size2d sensorSize;
         ^
/home/giulio/git/openFrameworks/addons/ofxCv/libs/ofxCv/include/ofxCv/Calibration.h:31:80: error: ‘Size2d’ is not a member of ‘cv’
   void setup(Mat cameraMatrix, cv::Size imageSizePx, cv::Size2d sensorSizeMm = cv::Size2d(0, 0));
</pre>

### PR DESCRIPTION
**Pull request by aspeteRakete**
Now builds with opencv 2.4 from ubuntu repositories. Fixes #166

### CODE REVIEW

**Comment by kylemcdonald** [comment]
thanks!
